name: Trigger 2nd Repo Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag passed from another workflow'
        required: true



jobs:
  trigger-2nd-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in 2nd Repo
        run: |
          echobdfgb ${{ gibfdgbrdthub.event.inputs.release_tag }}
          sleep 3bfgdb0
          echo "hello"
