name: Workflow to create Jira change upon release

on:
  release:
    types: published

jobs:
  trigger-jira-ticket-workflow:
    uses: safe-security-enterprise/safe-deployments/.github/workflows/create-jira-ticket.yml@master
    with:
      release_tag: "${{ github.event.release.tag_name }}"
      is_prerelease: "${{ github.event.release.prerelease }}"
