name: Source Workflow

on:
  release:
    types:
      - published

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Target Repository Workflow
        uses: actions/github-script@v6
        with:
          script: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer 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" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/deepak-mathpal/safe-deployments/dispatches \
              -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
    
