name: Trigger Target Workflow

on:
  release:
    types:
      - published

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger target repository workflow
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(process.env.PAT);
            await octokit.rest.repos.createDispatchEvent({
              owner: 'deepak-mathpal',
              repo: 'safe-deployments',
              event_type: 'trigger-event',
              client_payload: {
                tag: context.payload.release.tag_name,
                release_name: context.payload.release.name
              }
            });
        env:
          PAT: ${{ secrets.PAT }}
