name: Trigger 2nd Repo Workflow

on:
  workflow_dispatch:
  release:
      types: published

jobs:
  trigger-2nd-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in 2nd Repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.new }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/deepak-mathpal/newsafe/actions/workflows/triggered-by-jira.yml/dispatches \
          -d '{"ref":"main","inputs":{"release_tag":"${{ github.event.release.tag_name }}"}}'
