name: Source Workflow

on:
  release:
    types:
      - published

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Target Repository Workflow
        uses: actions/github-script@v6
        with:
          script: |
            curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"ref": "main", "inputs": {"release_tag": "v1.0.0", "release_name": "Initial Release"}}' \
            https://api.github.com/repos/deepak-mathpal/newsafe/actions/workflows/triggered-by-jira.yml.yml/dispatches

    
