name: Source Workflow

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: deepak-mathpal/newsafe
          ref: main 

  build-and-push:
    uses: deepak-mathpal/newsafe/.github/workflows/triggered-by-jira.yml@main
    secrets: ${{ secrets.PAT }}
